kind: pipeline
type: kubernetes
name: default

steps:
- name: Build-image-and-push
  image: plugins/docker
  settings:
    repo: mellena1/mandelbrot-wasm-ui
    auto_tag: true
    username: mellena1
    password:
      from_secret: password
